name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Build
    - name: Build
      run: cargo build --verbose
    # Clippy
    - name: Install Clippy
      run: rustup component add clippy
    - working-directory: ${{ matrix.conf.name }}
      name: Run Clippy
      run: cargo clippy
    # Tests
    - name: Run tests
      run: cargo test --verbose
